# https://embarkstudios.github.io/cargo-deny/cli/init.html

[graph]
all-features = true

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "Unicode-3.0",
    "MPL-2.0",
    "ISC",
    "BSD-3-Clause",
    "LicenseRef-ring"
]

[[licenses.clarify]]
name = "ring"
expression = "LicenseRef-ring"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 },
]

[bans]
multiple-versions = "allow"
# Currently tokio-monitor uses wildcards deps
# wildcards = "deny"

[sources]
unknown-registry = "deny"
# Currently tokio-monitor uses git deps
# unknown-git = "deny"
