# https://embarkstudios.github.io/cargo-deny/cli/init.html

[graph]
all-features = true

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "Unicode-3.0",
]
exceptions = [
    { allow = ["Unicode-3.0", "Unicode-DFS-2016"], crate = "unicode-ident" },
]

[bans]
multiple-versions = "allow"
# Currently tokio-monitor uses wildcards deps
# wildcards = "deny"

[sources]
unknown-registry = "deny"
# Currently tokio-monitor uses git deps
# unknown-git = "deny"
